include:
   - infra.yaml
services:
  web:
    build: .
    ports:
      - "8000:5000"
    develop:
      watch:
        - action: sync
          path: .
          target: /code
    volumes:
      - comptestvol:/var/lib/docker/volumes/comptestvol/_data:rw
volumes:
  comptestvol:
    external: true